/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module half_adder(a, b, sum, carry);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input a;
  wire a;
  input b;
  wire b;
  output carry;
  wire carry;
  output sum;
  wire sum;
  sky130_fd_sc_hd__and2_0 _4_ (
    .A(_1_),
    .B(_0_),
    .X(_2_)
  );
  sky130_fd_sc_hd__xor2_1 _5_ (
    .A(_1_),
    .B(_0_),
    .X(_3_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign sum = _3_;
  assign carry = _2_;
endmodule
