/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module seq_detector(clk, reset, din, detected);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  input clk;
  wire clk;
  wire [2:0] current_state;
  output detected;
  wire detected;
  input din;
  wire din;
  wire [2:0] next_state;
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _41_ (
    .A(_37_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__nor2_1 _42_ (
    .A(_27_),
    .B(_26_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__and2_0 _43_ (
    .A(_28_),
    .B(_31_),
    .X(_29_)
  );
  sky130_fd_sc_hd__a21oi_1 _44_ (
    .A1(_27_),
    .A2(_26_),
    .B1(_28_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__o21a_1 _45_ (
    .A1(_31_),
    .A2(_32_),
    .B1(_30_),
    .X(_34_)
  );
  sky130_fd_sc_hd__xnor2_1 _46_ (
    .A(_26_),
    .B(_30_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nor3_1 _47_ (
    .A(_28_),
    .B(_31_),
    .C(_33_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__and4b_1 _48_ (
    .A_N(_28_),
    .B(_30_),
    .C(_27_),
    .D(_26_),
    .X(_36_)
  );
  sky130_fd_sc_hd__clkinv_1 _49_ (
    .A(_37_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__clkinv_1 _50_ (
    .A(_37_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__dfrtp_1 _51_ (
    .CLK(clk),
    .D(next_state[0]),
    .Q(current_state[0]),
    .RESET_B(_38_)
  );
  sky130_fd_sc_hd__dfrtp_1 _52_ (
    .CLK(clk),
    .D(next_state[1]),
    .Q(current_state[1]),
    .RESET_B(_39_)
  );
  sky130_fd_sc_hd__dfrtp_1 _53_ (
    .CLK(clk),
    .D(next_state[2]),
    .Q(current_state[2]),
    .RESET_B(_40_)
  );
  assign _27_ = current_state[1];
  assign _26_ = current_state[0];
  assign _28_ = current_state[2];
  assign detected = _29_;
  assign _30_ = din;
  assign next_state[0] = _34_;
  assign next_state[1] = _35_;
  assign next_state[2] = _36_;
  assign _37_ = reset;
  assign _38_ = _23_;
  assign _39_ = _24_;
  assign _40_ = _25_;
endmodule
