/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module traffic_light(clk, reset, red, yellow, green);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  input clk;
  wire clk;
  wire [3:0] count;
  wire [2:0] current_state;
  output green;
  wire green;
  output red;
  wire red;
  input reset;
  wire reset;
  output yellow;
  wire yellow;
  sky130_fd_sc_hd__clkinv_1 _49_ (
    .A(_27_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__clkinv_1 _50_ (
    .A(_28_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__clkinv_1 _51_ (
    .A(_41_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nand2b_1 _52_ (
    .A_N(_29_),
    .B(_30_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__nor3_1 _53_ (
    .A(_13_),
    .B(_28_),
    .C(_35_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__mux2_1 _54_ (
    .A0(_32_),
    .A1(_31_),
    .S(_36_),
    .X(_18_)
  );
  sky130_fd_sc_hd__mux2_1 _55_ (
    .A0(_31_),
    .A1(_33_),
    .S(_36_),
    .X(_17_)
  );
  sky130_fd_sc_hd__mux2_1 _56_ (
    .A0(_33_),
    .A1(_32_),
    .S(_36_),
    .X(_19_)
  );
  sky130_fd_sc_hd__nand3_1 _57_ (
    .A(_27_),
    .B(_34_),
    .C(_35_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__o21ai_0 _58_ (
    .A1(_27_),
    .A2(_34_),
    .B1(_37_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__a21oi_1 _59_ (
    .A1(_27_),
    .A2(_28_),
    .B1(_29_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__nand3_1 _60_ (
    .A(_27_),
    .B(_28_),
    .C(_29_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__nor2b_1 _61_ (
    .A(_38_),
    .B_N(_39_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xor2_1 _62_ (
    .A(_30_),
    .B(_39_),
    .X(_40_)
  );
  sky130_fd_sc_hd__nor2_1 _63_ (
    .A(_36_),
    .B(_40_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__clkinv_1 _64_ (
    .A(_41_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__clkinv_1 _65_ (
    .A(_41_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__clkinv_1 _66_ (
    .A(_41_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__clkinv_1 _67_ (
    .A(_41_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__clkinv_1 _68_ (
    .A(_41_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__clkinv_1 _69_ (
    .A(_41_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__dfstp_2 _70_ (
    .CLK(clk),
    .D(_01_),
    .Q(current_state[0]),
    .SET_B(_42_)
  );
  sky130_fd_sc_hd__dfrtp_1 _71_ (
    .CLK(clk),
    .D(_02_),
    .Q(current_state[1]),
    .RESET_B(_43_)
  );
  sky130_fd_sc_hd__dfrtp_1 _72_ (
    .CLK(clk),
    .D(_03_),
    .Q(current_state[2]),
    .RESET_B(_44_)
  );
  sky130_fd_sc_hd__dfrtp_1 _73_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(count[0]),
    .RESET_B(_45_)
  );
  sky130_fd_sc_hd__dfrtp_1 _74_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(count[1]),
    .RESET_B(_46_)
  );
  sky130_fd_sc_hd__dfrtp_1 _75_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(count[2]),
    .RESET_B(_47_)
  );
  sky130_fd_sc_hd__dfrtp_1 _76_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(count[3]),
    .RESET_B(_48_)
  );
  assign green = current_state[1];
  assign red = current_state[0];
  assign yellow = current_state[2];
  assign _27_ = count[0];
  assign _28_ = count[1];
  assign _29_ = count[2];
  assign _30_ = count[3];
  assign _32_ = current_state[1];
  assign _31_ = current_state[0];
  assign _02_ = _18_;
  assign _33_ = current_state[2];
  assign _01_ = _17_;
  assign _03_ = _19_;
  assign _00_[0] = _13_;
  assign _00_[1] = _14_;
  assign _00_[2] = _15_;
  assign _00_[3] = _16_;
  assign _41_ = reset;
  assign _42_ = _20_;
  assign _43_ = _21_;
  assign _44_ = _22_;
  assign _45_ = _23_;
  assign _46_ = _24_;
  assign _47_ = _25_;
  assign _48_ = _26_;
endmodule
