/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module mux_4x1(i0, i1, i2, i3, s0, s1, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  input i0;
  wire i0;
  input i1;
  wire i1;
  input i2;
  wire i2;
  input i3;
  wire i3;
  input s0;
  wire s0;
  input s1;
  wire s1;
  output y;
  wire y;
  sky130_fd_sc_hd__mux4_2 _17_ (
    .A0(_10_),
    .A1(_11_),
    .A2(_12_),
    .A3(_13_),
    .S0(_14_),
    .S1(_15_),
    .X(_16_)
  );
  assign _14_ = s0;
  assign _15_ = s1;
  assign _10_ = i0;
  assign _11_ = i1;
  assign _12_ = i2;
  assign _13_ = i3;
  assign y = _16_;
endmodule
