/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module fa(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output sum;
  wire sum;
  sky130_fd_sc_hd__xor3_1 _10_ (
    .A(_01_),
    .B(_00_),
    .C(_02_),
    .X(_04_)
  );
  sky130_fd_sc_hd__maj3_1 _11_ (
    .A(_01_),
    .B(_00_),
    .C(_02_),
    .X(_03_)
  );
  assign _01_ = b;
  assign _00_ = a;
  assign _02_ = cin;
  assign sum = _04_;
  assign cout = _03_;
endmodule

module rca(a, b, cin, sum, cout);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  wire c1;
  wire c2;
  wire c3;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [3:0] sum;
  wire [3:0] sum;
  fa fa0 (
    .a(a[0]),
    .b(b[0]),
    .cin(cin),
    .cout(c1),
    .sum(sum[0])
  );
  fa fa1 (
    .a(a[1]),
    .b(b[1]),
    .cin(c1),
    .cout(c2),
    .sum(sum[1])
  );
  fa fa2 (
    .a(a[2]),
    .b(b[2]),
    .cin(c2),
    .cout(c3),
    .sum(sum[2])
  );
  fa fa3 (
    .a(a[3]),
    .b(b[3]),
    .cin(c3),
    .cout(cout),
    .sum(sum[3])
  );
endmodule
