/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module down_counter(clk, reset, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [3:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(_11_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(_17_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__xnor2_1 _25_ (
    .A(_11_),
    .B(_12_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor3_1 _26_ (
    .A(_11_),
    .B(_12_),
    .C(_13_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__o21ai_0 _27_ (
    .A1(_11_),
    .A2(_12_),
    .B1(_13_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nand2b_1 _28_ (
    .A_N(_15_),
    .B(_16_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xor2_1 _29_ (
    .A(_14_),
    .B(_15_),
    .X(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _30_ (
    .A(_17_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _31_ (
    .A(_17_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__clkinv_1 _32_ (
    .A(_17_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__dfstp_2 _33_ (
    .CLK(clk),
    .D(_18_[0]),
    .Q(count[0]),
    .SET_B(_19_)
  );
  sky130_fd_sc_hd__dfstp_2 _34_ (
    .CLK(clk),
    .D(_18_[1]),
    .Q(count[1]),
    .SET_B(_20_)
  );
  sky130_fd_sc_hd__dfstp_2 _35_ (
    .CLK(clk),
    .D(_18_[2]),
    .Q(count[2]),
    .SET_B(_21_)
  );
  sky130_fd_sc_hd__dfstp_2 _36_ (
    .CLK(clk),
    .D(_18_[3]),
    .Q(count[3]),
    .SET_B(_22_)
  );
  assign _11_ = count[0];
  assign _18_[0] = _03_;
  assign _12_ = count[1];
  assign _18_[1] = _04_;
  assign _13_ = count[2];
  assign _18_[2] = _05_;
  assign _14_ = count[3];
  assign _18_[3] = _06_;
  assign _17_ = reset;
  assign _19_ = _07_;
  assign _20_ = _08_;
  assign _21_ = _09_;
  assign _22_ = _10_;
endmodule
