/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module shift_register(clk, reset, din, dout);
  reg \$auto$verilog_backend.cc:2184:dump_module$2  = 0;
  reg [7:0] _0_;
  input clk;
  wire clk;
  input din;
  wire din;
  output [7:0] dout;
  reg [7:0] dout;
  input reset;
  wire reset;
  always @* begin
    if (\$auto$verilog_backend.cc:2184:dump_module$2 ) begin end
    _0_ = dout;
    casez (reset)
      1'h1:
          _0_ = 8'h00;
      default:
          _0_ = { dout[6:0], din };
    endcase
  end
  always @(posedge clk) begin
      dout <= _0_;
  end
  always @(posedge reset) begin
      dout <= _0_;
  end
endmodule
