###############################################################################
# Created by write_sdc
# Thu Apr 16 13:22:52 2026
###############################################################################
current_design iiitb_rv32i
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 20.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {RN}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {NPC[9]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[10]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[11]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[12]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[13]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[14]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[15]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[16]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[17]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[18]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[19]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[20]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[21]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[22]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[23]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[24]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[25]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[26]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[27]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[28]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[29]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[30]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[31]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[8]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {WB_OUT[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {NPC[31]}]
set_load -pin_load 0.0334 [get_ports {NPC[30]}]
set_load -pin_load 0.0334 [get_ports {NPC[29]}]
set_load -pin_load 0.0334 [get_ports {NPC[28]}]
set_load -pin_load 0.0334 [get_ports {NPC[27]}]
set_load -pin_load 0.0334 [get_ports {NPC[26]}]
set_load -pin_load 0.0334 [get_ports {NPC[25]}]
set_load -pin_load 0.0334 [get_ports {NPC[24]}]
set_load -pin_load 0.0334 [get_ports {NPC[23]}]
set_load -pin_load 0.0334 [get_ports {NPC[22]}]
set_load -pin_load 0.0334 [get_ports {NPC[21]}]
set_load -pin_load 0.0334 [get_ports {NPC[20]}]
set_load -pin_load 0.0334 [get_ports {NPC[19]}]
set_load -pin_load 0.0334 [get_ports {NPC[18]}]
set_load -pin_load 0.0334 [get_ports {NPC[17]}]
set_load -pin_load 0.0334 [get_ports {NPC[16]}]
set_load -pin_load 0.0334 [get_ports {NPC[15]}]
set_load -pin_load 0.0334 [get_ports {NPC[14]}]
set_load -pin_load 0.0334 [get_ports {NPC[13]}]
set_load -pin_load 0.0334 [get_ports {NPC[12]}]
set_load -pin_load 0.0334 [get_ports {NPC[11]}]
set_load -pin_load 0.0334 [get_ports {NPC[10]}]
set_load -pin_load 0.0334 [get_ports {NPC[9]}]
set_load -pin_load 0.0334 [get_ports {NPC[8]}]
set_load -pin_load 0.0334 [get_ports {NPC[7]}]
set_load -pin_load 0.0334 [get_ports {NPC[6]}]
set_load -pin_load 0.0334 [get_ports {NPC[5]}]
set_load -pin_load 0.0334 [get_ports {NPC[4]}]
set_load -pin_load 0.0334 [get_ports {NPC[3]}]
set_load -pin_load 0.0334 [get_ports {NPC[2]}]
set_load -pin_load 0.0334 [get_ports {NPC[1]}]
set_load -pin_load 0.0334 [get_ports {NPC[0]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[31]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[30]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[29]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[28]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[27]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[26]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[25]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[24]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[23]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[22]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[21]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[20]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[19]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[18]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[17]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[16]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[15]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[14]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[13]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[12]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[11]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[10]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[9]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[8]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[7]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[6]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[5]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[4]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[3]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[2]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[1]}]
set_load -pin_load 0.0334 [get_ports {WB_OUT[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {RN}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 10.0000 [current_design]
