/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module uart_rx(clk, reset, rx, data, done);
  wire [7:0] _000_;
  wire [2:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire [2:0] bit_count;
  input clk;
  wire clk;
  output [7:0] data;
  wire [7:0] data;
  output done;
  wire done;
  input reset;
  wire reset;
  input rx;
  wire rx;
  wire [3:0] state;
  sky130_fd_sc_hd__clkinv_1 _195_ (
    .A(_120_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__clkinv_1 _196_ (
    .A(_119_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__clkinv_1 _197_ (
    .A(_118_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__clkinv_1 _198_ (
    .A(_164_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__clkinv_1 _199_ (
    .A(_161_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2b_1 _200_ (
    .A_N(_162_),
    .B(_166_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o21ai_0 _201_ (
    .A1(_166_),
    .A2(_163_),
    .B1(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a22o_1 _202_ (
    .A1(_166_),
    .A2(_162_),
    .B1(_135_),
    .B2(_129_),
    .X(_117_)
  );
  sky130_fd_sc_hd__nor3_1 _203_ (
    .A(_120_),
    .B(_119_),
    .C(_118_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__or3_1 _204_ (
    .A(_120_),
    .B(_119_),
    .C(_118_),
    .X(_137_)
  );
  sky130_fd_sc_hd__o21a_1 _205_ (
    .A1(_119_),
    .A2(_118_),
    .B1(_120_),
    .X(_138_)
  );
  sky130_fd_sc_hd__nand3_1 _206_ (
    .A(_120_),
    .B(_119_),
    .C(_118_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nor3_1 _207_ (
    .A(_166_),
    .B(_165_),
    .C(_163_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__or3_1 _208_ (
    .A(_166_),
    .B(_165_),
    .C(_163_),
    .X(_141_)
  );
  sky130_fd_sc_hd__o21ai_0 _209_ (
    .A1(_139_),
    .A2(_141_),
    .B1(_128_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand2_1 _210_ (
    .A(_162_),
    .B(_137_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__xor2_1 _211_ (
    .A(_119_),
    .B(_118_),
    .X(_144_)
  );
  sky130_fd_sc_hd__nand3_1 _212_ (
    .A(_119_),
    .B(_118_),
    .C(_162_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o21ai_0 _213_ (
    .A1(_136_),
    .A2(_138_),
    .B1(_140_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o21ai_0 _214_ (
    .A1(_145_),
    .A2(_146_),
    .B1(_142_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o41ai_1 _215_ (
    .A1(_130_),
    .A2(_131_),
    .A3(_118_),
    .A4(_141_),
    .B1(_127_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand3_1 _216_ (
    .A(_119_),
    .B(_132_),
    .C(_162_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__o21ai_0 _217_ (
    .A1(_146_),
    .A2(_148_),
    .B1(_147_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o41ai_1 _218_ (
    .A1(_130_),
    .A2(_119_),
    .A3(_132_),
    .A4(_141_),
    .B1(_126_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand3_1 _219_ (
    .A(_131_),
    .B(_118_),
    .C(_162_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _220_ (
    .A1(_146_),
    .A2(_150_),
    .B1(_149_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__o41ai_1 _221_ (
    .A1(_130_),
    .A2(_119_),
    .A3(_118_),
    .A4(_141_),
    .B1(_125_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o41ai_1 _222_ (
    .A1(_119_),
    .A2(_118_),
    .A3(_141_),
    .A4(_143_),
    .B1(_151_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__or3_1 _223_ (
    .A(_136_),
    .B(_138_),
    .C(_141_),
    .X(_152_)
  );
  sky130_fd_sc_hd__o41ai_1 _224_ (
    .A1(_120_),
    .A2(_131_),
    .A3(_132_),
    .A4(_141_),
    .B1(_124_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o21ai_0 _225_ (
    .A1(_145_),
    .A2(_152_),
    .B1(_153_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__o41ai_1 _226_ (
    .A1(_120_),
    .A2(_131_),
    .A3(_118_),
    .A4(_141_),
    .B1(_123_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__o21ai_0 _227_ (
    .A1(_148_),
    .A2(_152_),
    .B1(_154_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__o41ai_1 _228_ (
    .A1(_120_),
    .A2(_119_),
    .A3(_132_),
    .A4(_141_),
    .B1(_122_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o21ai_0 _229_ (
    .A1(_150_),
    .A2(_152_),
    .B1(_155_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nand3_1 _230_ (
    .A(_162_),
    .B(_136_),
    .C(_140_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o21ai_0 _231_ (
    .A1(_137_),
    .A2(_141_),
    .B1(_121_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _232_ (
    .A(_156_),
    .B(_157_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__a31oi_1 _233_ (
    .A1(_119_),
    .A2(_118_),
    .A3(_164_),
    .B1(_120_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nor2b_1 _234_ (
    .A(_164_),
    .B_N(_165_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__nor2_1 _235_ (
    .A(_158_),
    .B(_159_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21oi_1 _236_ (
    .A1(_164_),
    .A2(_139_),
    .B1(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a22o_1 _237_ (
    .A1(_164_),
    .A2(_144_),
    .B1(_160_),
    .B2(_119_),
    .X(_107_)
  );
  sky130_fd_sc_hd__mux2_1 _238_ (
    .A0(_164_),
    .A1(_160_),
    .S(_118_),
    .X(_106_)
  );
  sky130_fd_sc_hd__a21o_1 _239_ (
    .A1(_164_),
    .A2(_139_),
    .B1(_165_),
    .X(_088_)
  );
  sky130_fd_sc_hd__o21ai_0 _240_ (
    .A1(_133_),
    .A2(_139_),
    .B1(_134_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__o21a_1 _241_ (
    .A1(_166_),
    .A2(_163_),
    .B1(_162_),
    .X(_086_)
  );
  sky130_fd_sc_hd__nor2b_1 _242_ (
    .A(_162_),
    .B_N(_163_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__clkinv_1 _243_ (
    .A(_161_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__clkinv_1 _244_ (
    .A(_161_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__clkinv_1 _245_ (
    .A(_161_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__clkinv_1 _246_ (
    .A(_161_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _247_ (
    .A(_161_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__clkinv_1 _248_ (
    .A(_161_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__clkinv_1 _249_ (
    .A(_161_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__clkinv_1 _250_ (
    .A(_161_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__clkinv_1 _251_ (
    .A(_161_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__clkinv_1 _252_ (
    .A(_161_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__clkinv_1 _253_ (
    .A(_161_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__clkinv_1 _254_ (
    .A(_161_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__clkinv_1 _255_ (
    .A(_161_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__clkinv_1 _256_ (
    .A(_161_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__clkinv_1 _257_ (
    .A(_161_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__dfrtp_1 _258_ (
    .CLK(clk),
    .D(_183_),
    .Q(bit_count[0]),
    .RESET_B(_167_)
  );
  sky130_fd_sc_hd__dfrtp_1 _259_ (
    .CLK(clk),
    .D(_184_),
    .Q(bit_count[1]),
    .RESET_B(_168_)
  );
  sky130_fd_sc_hd__dfrtp_1 _260_ (
    .CLK(clk),
    .D(_185_),
    .Q(bit_count[2]),
    .RESET_B(_169_)
  );
  sky130_fd_sc_hd__dfstp_2 _261_ (
    .CLK(clk),
    .D(_002_),
    .Q(state[0]),
    .SET_B(_170_)
  );
  sky130_fd_sc_hd__dfrtp_1 _262_ (
    .CLK(clk),
    .D(_004_),
    .Q(state[1]),
    .RESET_B(_171_)
  );
  sky130_fd_sc_hd__dfrtp_1 _263_ (
    .CLK(clk),
    .D(_003_),
    .Q(state[2]),
    .RESET_B(_172_)
  );
  sky130_fd_sc_hd__dfrtp_1 _264_ (
    .CLK(clk),
    .D(_005_),
    .Q(state[3]),
    .RESET_B(_173_)
  );
  sky130_fd_sc_hd__dfrtp_1 _265_ (
    .CLK(clk),
    .D(_186_),
    .Q(data[0]),
    .RESET_B(_174_)
  );
  sky130_fd_sc_hd__dfrtp_1 _266_ (
    .CLK(clk),
    .D(_187_),
    .Q(data[1]),
    .RESET_B(_175_)
  );
  sky130_fd_sc_hd__dfrtp_1 _267_ (
    .CLK(clk),
    .D(_188_),
    .Q(data[2]),
    .RESET_B(_176_)
  );
  sky130_fd_sc_hd__dfrtp_1 _268_ (
    .CLK(clk),
    .D(_189_),
    .Q(data[3]),
    .RESET_B(_177_)
  );
  sky130_fd_sc_hd__dfrtp_1 _269_ (
    .CLK(clk),
    .D(_190_),
    .Q(data[4]),
    .RESET_B(_178_)
  );
  sky130_fd_sc_hd__dfrtp_1 _270_ (
    .CLK(clk),
    .D(_191_),
    .Q(data[5]),
    .RESET_B(_179_)
  );
  sky130_fd_sc_hd__dfrtp_1 _271_ (
    .CLK(clk),
    .D(_192_),
    .Q(data[6]),
    .RESET_B(_180_)
  );
  sky130_fd_sc_hd__dfrtp_1 _272_ (
    .CLK(clk),
    .D(_193_),
    .Q(data[7]),
    .RESET_B(_181_)
  );
  sky130_fd_sc_hd__dfrtp_1 _273_ (
    .CLK(clk),
    .D(_194_),
    .Q(done),
    .RESET_B(_182_)
  );
  assign _129_ = done;
  assign _166_ = state[3];
  assign _194_ = _117_;
  assign _128_ = data[7];
  assign _193_ = _116_;
  assign _127_ = data[6];
  assign _192_ = _115_;
  assign _126_ = data[5];
  assign _191_ = _114_;
  assign _125_ = data[4];
  assign _190_ = _113_;
  assign _124_ = data[3];
  assign _189_ = _112_;
  assign _123_ = data[2];
  assign _188_ = _111_;
  assign _122_ = data[1];
  assign _187_ = _110_;
  assign _121_ = data[0];
  assign _186_ = _109_;
  assign _120_ = bit_count[2];
  assign _185_ = _108_;
  assign _119_ = bit_count[1];
  assign _184_ = _107_;
  assign _118_ = bit_count[0];
  assign _183_ = _106_;
  assign _164_ = state[1];
  assign _165_ = state[2];
  assign _004_ = _088_;
  assign _163_ = state[0];
  assign _162_ = rx;
  assign _005_ = _089_;
  assign _002_ = _086_;
  assign _003_ = _087_;
  assign _161_ = reset;
  assign _167_ = _090_;
  assign _168_ = _091_;
  assign _169_ = _092_;
  assign _170_ = _093_;
  assign _171_ = _094_;
  assign _172_ = _095_;
  assign _173_ = _096_;
  assign _174_ = _097_;
  assign _175_ = _098_;
  assign _176_ = _099_;
  assign _177_ = _100_;
  assign _178_ = _101_;
  assign _179_ = _102_;
  assign _180_ = _103_;
  assign _181_ = _104_;
  assign _182_ = _105_;
endmodule
