/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module uart_tx(clk, reset, start, data, tx, done);
  wire [2:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire [1:0] _115_;
  wire _116_;
  wire [2:0] bit_count;
  input clk;
  wire clk;
  input [7:0] data;
  wire [7:0] data;
  wire [7:0] data_reg;
  output done;
  wire done;
  input reset;
  wire reset;
  input start;
  wire start;
  wire [3:0] state;
  output tx;
  wire tx;
  sky130_fd_sc_hd__clkinv_1 _117_ (
    .A(_053_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _118_ (
    .A(_052_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__clkinv_1 _119_ (
    .A(_051_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _120_ (
    .A(_091_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__clkinv_1 _121_ (
    .A(_089_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _122_ (
    .A(_088_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2b_1 _123_ (
    .A(_091_),
    .B_N(_092_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o32ai_1 _124_ (
    .A1(_072_),
    .A2(_073_),
    .A3(_074_),
    .B1(_076_),
    .B2(_071_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand3_1 _125_ (
    .A(_053_),
    .B(_052_),
    .C(_051_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a211oi_1 _126_ (
    .A1(_091_),
    .A2(_077_),
    .B1(_076_),
    .C1(_072_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a21oi_1 _127_ (
    .A1(_052_),
    .A2(_051_),
    .B1(_074_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o22a_1 _128_ (
    .A1(_052_),
    .A2(_051_),
    .B1(_078_),
    .B2(_079_),
    .X(_049_)
  );
  sky130_fd_sc_hd__a211o_1 _129_ (
    .A1(_091_),
    .A2(_077_),
    .B1(_076_),
    .C1(_073_),
    .X(_080_)
  );
  sky130_fd_sc_hd__o21ai_0 _130_ (
    .A1(_051_),
    .A2(_074_),
    .B1(_080_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _131_ (
    .A(_093_),
    .B(_090_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a21o_1 _132_ (
    .A1(_070_),
    .A2(_081_),
    .B1(_093_),
    .X(_047_)
  );
  sky130_fd_sc_hd__a21o_1 _133_ (
    .A1(_091_),
    .A2(_077_),
    .B1(_092_),
    .X(_029_)
  );
  sky130_fd_sc_hd__and2_0 _134_ (
    .A(_090_),
    .B(_089_),
    .X(_026_)
  );
  sky130_fd_sc_hd__a21o_1 _135_ (
    .A1(_090_),
    .A2(_075_),
    .B1(_093_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux4_2 _136_ (
    .A0(_062_),
    .A1(_063_),
    .A2(_064_),
    .A3(_065_),
    .S0(_051_),
    .S1(_052_),
    .X(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _137_ (
    .A(_053_),
    .B(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__mux4_2 _138_ (
    .A0(_066_),
    .A1(_067_),
    .A2(_068_),
    .A3(_069_),
    .S0(_051_),
    .S1(_052_),
    .X(_084_)
  );
  sky130_fd_sc_hd__o21ai_0 _139_ (
    .A1(_071_),
    .A2(_084_),
    .B1(_091_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o21ai_0 _140_ (
    .A1(_083_),
    .A2(_085_),
    .B1(_081_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nor2_1 _141_ (
    .A(_074_),
    .B(_077_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _142_ (
    .A(_030_),
    .B(_026_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__mux2_1 _143_ (
    .A0(_054_),
    .A1(_062_),
    .S(_086_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _144_ (
    .A0(_055_),
    .A1(_063_),
    .S(_086_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _145_ (
    .A0(_056_),
    .A1(_064_),
    .S(_086_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _146_ (
    .A0(_057_),
    .A1(_065_),
    .S(_086_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _147_ (
    .A0(_058_),
    .A1(_066_),
    .S(_086_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _148_ (
    .A0(_059_),
    .A1(_067_),
    .S(_086_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _149_ (
    .A0(_060_),
    .A1(_068_),
    .S(_086_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _150_ (
    .A0(_061_),
    .A1(_069_),
    .S(_086_),
    .X(_046_)
  );
  sky130_fd_sc_hd__clkinv_1 _151_ (
    .A(_088_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _152_ (
    .A(_088_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _153_ (
    .A(_088_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _154_ (
    .A(_088_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__clkinv_1 _155_ (
    .A(_088_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _156_ (
    .A(_088_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _157_ (
    .A(_088_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkinv_1 _158_ (
    .A(_088_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__dfxtp_1 _159_ (
    .CLK(clk),
    .D(_103_),
    .Q(data_reg[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _160_ (
    .CLK(clk),
    .D(_104_),
    .Q(data_reg[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _161_ (
    .CLK(clk),
    .D(_105_),
    .Q(data_reg[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _162_ (
    .CLK(clk),
    .D(_106_),
    .Q(data_reg[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _163_ (
    .CLK(clk),
    .D(_107_),
    .Q(data_reg[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _164_ (
    .CLK(clk),
    .D(_108_),
    .Q(data_reg[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _165_ (
    .CLK(clk),
    .D(_109_),
    .Q(data_reg[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _166_ (
    .CLK(clk),
    .D(_110_),
    .Q(data_reg[7])
  );
  sky130_fd_sc_hd__dfstp_2 _167_ (
    .CLK(clk),
    .D(_003_),
    .Q(state[0]),
    .SET_B(_094_)
  );
  sky130_fd_sc_hd__dfrtp_1 _168_ (
    .CLK(clk),
    .D(_004_),
    .Q(state[1]),
    .RESET_B(_095_)
  );
  sky130_fd_sc_hd__dfrtp_1 _169_ (
    .CLK(clk),
    .D(_001_),
    .Q(state[2]),
    .RESET_B(_096_)
  );
  sky130_fd_sc_hd__dfrtp_1 _170_ (
    .CLK(clk),
    .D(_002_),
    .Q(state[3]),
    .RESET_B(_097_)
  );
  sky130_fd_sc_hd__dfstp_2 _171_ (
    .CLK(clk),
    .D(_116_),
    .Q(tx),
    .SET_B(_098_)
  );
  sky130_fd_sc_hd__dfrtp_1 _172_ (
    .CLK(clk),
    .D(_111_),
    .Q(done),
    .RESET_B(_099_)
  );
  sky130_fd_sc_hd__dfrtp_1 _173_ (
    .CLK(clk),
    .D(_112_),
    .Q(bit_count[0]),
    .RESET_B(_100_)
  );
  sky130_fd_sc_hd__dfrtp_1 _174_ (
    .CLK(clk),
    .D(_113_),
    .Q(bit_count[1]),
    .RESET_B(_101_)
  );
  sky130_fd_sc_hd__dfrtp_1 _175_ (
    .CLK(clk),
    .D(_114_),
    .Q(bit_count[2]),
    .RESET_B(_102_)
  );
  assign _053_ = bit_count[2];
  assign _114_ = _050_;
  assign _052_ = bit_count[1];
  assign _113_ = _049_;
  assign _051_ = bit_count[0];
  assign _112_ = _048_;
  assign _070_ = done;
  assign _093_ = state[3];
  assign _111_ = _047_;
  assign _090_ = state[0];
  assign _091_ = state[1];
  assign _092_ = state[2];
  assign _004_ = _029_;
  assign _089_ = start;
  assign _001_ = _026_;
  assign _088_ = reset;
  assign _003_ = _028_;
  assign _062_ = data_reg[0];
  assign _063_ = data_reg[1];
  assign _064_ = data_reg[2];
  assign _065_ = data_reg[3];
  assign _066_ = data_reg[4];
  assign _067_ = data_reg[5];
  assign _068_ = data_reg[6];
  assign _069_ = data_reg[7];
  assign _116_ = _087_;
  assign _002_ = _027_;
  assign _054_ = data[0];
  assign _103_ = _039_;
  assign _055_ = data[1];
  assign _104_ = _040_;
  assign _056_ = data[2];
  assign _105_ = _041_;
  assign _057_ = data[3];
  assign _106_ = _042_;
  assign _058_ = data[4];
  assign _107_ = _043_;
  assign _059_ = data[5];
  assign _108_ = _044_;
  assign _060_ = data[6];
  assign _109_ = _045_;
  assign _061_ = data[7];
  assign _110_ = _046_;
  assign _094_ = _030_;
  assign _095_ = _031_;
  assign _096_ = _032_;
  assign _097_ = _033_;
  assign _098_ = _034_;
  assign _099_ = _035_;
  assign _100_ = _036_;
  assign _101_ = _037_;
  assign _102_ = _038_;
endmodule
