/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module uart_top(clk, reset, start, tx_data, tx_done, rx_done, rx_data);
  wire [7:0] _000_;
  wire [2:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire [2:0] _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire [1:0] _304_;
  wire _305_;
  input clk;
  wire clk;
  input reset;
  wire reset;
  output [7:0] rx_data;
  wire [7:0] rx_data;
  output rx_done;
  wire rx_done;
  wire [2:0] \rx_inst.bit_count ;
  wire \rx_inst.clk ;
  wire [7:0] \rx_inst.data ;
  wire \rx_inst.done ;
  wire \rx_inst.reset ;
  wire \rx_inst.rx ;
  wire [3:0] \rx_inst.state ;
  input start;
  wire start;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  output tx_done;
  wire tx_done;
  wire [2:0] \tx_inst.bit_count ;
  wire \tx_inst.clk ;
  wire [7:0] \tx_inst.data ;
  wire [7:0] \tx_inst.data_reg ;
  wire \tx_inst.done ;
  wire \tx_inst.reset ;
  wire \tx_inst.start ;
  wire [3:0] \tx_inst.state ;
  wire \tx_inst.tx ;
  wire tx_line;
  sky130_fd_sc_hd__clkinv_1 _306_ (
    .A(_116_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__clkinv_1 _307_ (
    .A(_115_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__clkinv_1 _308_ (
    .A(_114_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__clkinv_1 _309_ (
    .A(_158_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__clkinv_1 _310_ (
    .A(_155_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2b_1 _311_ (
    .A_N(_156_),
    .B(_160_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _312_ (
    .A1(_160_),
    .A2(_157_),
    .B1(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a22o_1 _313_ (
    .A1(_160_),
    .A2(_156_),
    .B1(_131_),
    .B2(_125_),
    .X(_113_)
  );
  sky130_fd_sc_hd__nor3_1 _314_ (
    .A(_116_),
    .B(_115_),
    .C(_114_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__o21a_1 _315_ (
    .A1(_115_),
    .A2(_114_),
    .B1(_116_),
    .X(_133_)
  );
  sky130_fd_sc_hd__nand3_1 _316_ (
    .A(_116_),
    .B(_115_),
    .C(_114_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nor3_1 _317_ (
    .A(_160_),
    .B(_159_),
    .C(_157_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__or3_1 _318_ (
    .A(_160_),
    .B(_159_),
    .C(_157_),
    .X(_136_)
  );
  sky130_fd_sc_hd__o21ai_0 _319_ (
    .A1(_134_),
    .A2(_136_),
    .B1(_124_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__xor2_1 _320_ (
    .A(_115_),
    .B(_114_),
    .X(_138_)
  );
  sky130_fd_sc_hd__nand3_1 _321_ (
    .A(_115_),
    .B(_114_),
    .C(_156_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o21ai_0 _322_ (
    .A1(_132_),
    .A2(_133_),
    .B1(_135_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__o21ai_0 _323_ (
    .A1(_139_),
    .A2(_140_),
    .B1(_137_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__o41ai_1 _324_ (
    .A1(_126_),
    .A2(_127_),
    .A3(_114_),
    .A4(_136_),
    .B1(_123_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__o211ai_1 _325_ (
    .A1(_116_),
    .A2(_115_),
    .B1(_128_),
    .C1(_156_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nand3_1 _326_ (
    .A(_115_),
    .B(_128_),
    .C(_156_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__o21ai_0 _327_ (
    .A1(_140_),
    .A2(_143_),
    .B1(_141_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__o41ai_1 _328_ (
    .A1(_126_),
    .A2(_115_),
    .A3(_128_),
    .A4(_136_),
    .B1(_122_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand3_1 _329_ (
    .A(_127_),
    .B(_114_),
    .C(_156_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o21ai_0 _330_ (
    .A1(_140_),
    .A2(_145_),
    .B1(_144_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o41ai_1 _331_ (
    .A1(_126_),
    .A2(_115_),
    .A3(_114_),
    .A4(_136_),
    .B1(_121_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o31ai_1 _332_ (
    .A1(_136_),
    .A2(_138_),
    .A3(_142_),
    .B1(_146_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__or3_1 _333_ (
    .A(_132_),
    .B(_133_),
    .C(_136_),
    .X(_147_)
  );
  sky130_fd_sc_hd__o41ai_1 _334_ (
    .A1(_116_),
    .A2(_127_),
    .A3(_128_),
    .A4(_136_),
    .B1(_120_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__o21ai_0 _335_ (
    .A1(_139_),
    .A2(_147_),
    .B1(_148_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o41ai_1 _336_ (
    .A1(_116_),
    .A2(_127_),
    .A3(_114_),
    .A4(_136_),
    .B1(_119_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o21ai_0 _337_ (
    .A1(_143_),
    .A2(_147_),
    .B1(_149_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__o41ai_1 _338_ (
    .A1(_116_),
    .A2(_115_),
    .A3(_128_),
    .A4(_136_),
    .B1(_118_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__o21ai_0 _339_ (
    .A1(_145_),
    .A2(_147_),
    .B1(_150_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _340_ (
    .A(_132_),
    .B(_135_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__mux2_1 _341_ (
    .A0(_156_),
    .A1(_117_),
    .S(_151_),
    .X(_105_)
  );
  sky130_fd_sc_hd__a31oi_1 _342_ (
    .A1(_115_),
    .A2(_114_),
    .A3(_158_),
    .B1(_116_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2b_1 _343_ (
    .A(_158_),
    .B_N(_159_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nor2_1 _344_ (
    .A(_152_),
    .B(_153_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__a21oi_1 _345_ (
    .A1(_158_),
    .A2(_134_),
    .B1(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a22o_1 _346_ (
    .A1(_158_),
    .A2(_138_),
    .B1(_154_),
    .B2(_115_),
    .X(_103_)
  );
  sky130_fd_sc_hd__mux2_1 _347_ (
    .A0(_158_),
    .A1(_154_),
    .S(_114_),
    .X(_102_)
  );
  sky130_fd_sc_hd__o21ai_0 _348_ (
    .A1(_129_),
    .A2(_134_),
    .B1(_130_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a21o_1 _349_ (
    .A1(_158_),
    .A2(_134_),
    .B1(_159_),
    .X(_084_)
  );
  sky130_fd_sc_hd__nor2b_1 _350_ (
    .A(_156_),
    .B_N(_157_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__o21a_1 _351_ (
    .A1(_160_),
    .A2(_157_),
    .B1(_156_),
    .X(_082_)
  );
  sky130_fd_sc_hd__clkinv_1 _352_ (
    .A(_155_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__clkinv_1 _353_ (
    .A(_155_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__clkinv_1 _354_ (
    .A(_155_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _355_ (
    .A(_155_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__clkinv_1 _356_ (
    .A(_155_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__clkinv_1 _357_ (
    .A(_155_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__clkinv_1 _358_ (
    .A(_155_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__clkinv_1 _359_ (
    .A(_155_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _360_ (
    .A(_155_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__clkinv_1 _361_ (
    .A(_155_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__clkinv_1 _362_ (
    .A(_155_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__clkinv_1 _363_ (
    .A(_155_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__clkinv_1 _364_ (
    .A(_155_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__clkinv_1 _365_ (
    .A(_155_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__clkinv_1 _366_ (
    .A(_155_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__dfstp_2 _367_ (
    .CLK(\rx_inst.clk ),
    .D(_002_),
    .Q(\rx_inst.state [0]),
    .SET_B(_161_)
  );
  sky130_fd_sc_hd__dfrtp_1 _368_ (
    .CLK(\rx_inst.clk ),
    .D(_004_),
    .Q(\rx_inst.state [1]),
    .RESET_B(_162_)
  );
  sky130_fd_sc_hd__dfrtp_1 _369_ (
    .CLK(\rx_inst.clk ),
    .D(_003_),
    .Q(\rx_inst.state [2]),
    .RESET_B(_163_)
  );
  sky130_fd_sc_hd__dfrtp_1 _370_ (
    .CLK(\rx_inst.clk ),
    .D(_005_),
    .Q(\rx_inst.state [3]),
    .RESET_B(_164_)
  );
  sky130_fd_sc_hd__dfrtp_1 _371_ (
    .CLK(\rx_inst.clk ),
    .D(_177_),
    .Q(\rx_inst.bit_count [0]),
    .RESET_B(_165_)
  );
  sky130_fd_sc_hd__dfrtp_1 _372_ (
    .CLK(\rx_inst.clk ),
    .D(_178_),
    .Q(\rx_inst.bit_count [1]),
    .RESET_B(_166_)
  );
  sky130_fd_sc_hd__dfrtp_1 _373_ (
    .CLK(\rx_inst.clk ),
    .D(_179_),
    .Q(\rx_inst.bit_count [2]),
    .RESET_B(_167_)
  );
  sky130_fd_sc_hd__dfrtp_1 _374_ (
    .CLK(\rx_inst.clk ),
    .D(_180_),
    .Q(\rx_inst.data [0]),
    .RESET_B(_168_)
  );
  sky130_fd_sc_hd__dfrtp_1 _375_ (
    .CLK(\rx_inst.clk ),
    .D(_181_),
    .Q(\rx_inst.data [1]),
    .RESET_B(_169_)
  );
  sky130_fd_sc_hd__dfrtp_1 _376_ (
    .CLK(\rx_inst.clk ),
    .D(_182_),
    .Q(\rx_inst.data [2]),
    .RESET_B(_170_)
  );
  sky130_fd_sc_hd__dfrtp_1 _377_ (
    .CLK(\rx_inst.clk ),
    .D(_183_),
    .Q(\rx_inst.data [3]),
    .RESET_B(_171_)
  );
  sky130_fd_sc_hd__dfrtp_1 _378_ (
    .CLK(\rx_inst.clk ),
    .D(_184_),
    .Q(\rx_inst.data [4]),
    .RESET_B(_172_)
  );
  sky130_fd_sc_hd__dfrtp_1 _379_ (
    .CLK(\rx_inst.clk ),
    .D(_185_),
    .Q(\rx_inst.data [5]),
    .RESET_B(_173_)
  );
  sky130_fd_sc_hd__dfrtp_1 _380_ (
    .CLK(\rx_inst.clk ),
    .D(_186_),
    .Q(\rx_inst.data [6]),
    .RESET_B(_174_)
  );
  sky130_fd_sc_hd__dfrtp_1 _381_ (
    .CLK(\rx_inst.clk ),
    .D(_187_),
    .Q(\rx_inst.data [7]),
    .RESET_B(_175_)
  );
  sky130_fd_sc_hd__dfrtp_1 _382_ (
    .CLK(\rx_inst.clk ),
    .D(_188_),
    .Q(\rx_inst.done ),
    .RESET_B(_176_)
  );
  sky130_fd_sc_hd__clkinv_1 _383_ (
    .A(_242_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__clkinv_1 _384_ (
    .A(_241_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__clkinv_1 _385_ (
    .A(_240_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__clkinv_1 _386_ (
    .A(_280_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__clkinv_1 _387_ (
    .A(_278_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__clkinv_1 _388_ (
    .A(_277_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nor2b_1 _389_ (
    .A(_280_),
    .B_N(_281_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__o32ai_1 _390_ (
    .A1(_261_),
    .A2(_262_),
    .A3(_263_),
    .B1(_265_),
    .B2(_260_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nand3_1 _391_ (
    .A(_242_),
    .B(_241_),
    .C(_240_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__a211oi_1 _392_ (
    .A1(_280_),
    .A2(_266_),
    .B1(_265_),
    .C1(_261_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__a21oi_1 _393_ (
    .A1(_241_),
    .A2(_240_),
    .B1(_263_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__o22a_1 _394_ (
    .A1(_241_),
    .A2(_240_),
    .B1(_267_),
    .B2(_268_),
    .X(_238_)
  );
  sky130_fd_sc_hd__a211o_1 _395_ (
    .A1(_280_),
    .A2(_266_),
    .B1(_265_),
    .C1(_262_),
    .X(_269_)
  );
  sky130_fd_sc_hd__o21ai_0 _396_ (
    .A1(_240_),
    .A2(_263_),
    .B1(_269_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nor2_1 _397_ (
    .A(_282_),
    .B(_279_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__a21o_1 _398_ (
    .A1(_259_),
    .A2(_270_),
    .B1(_282_),
    .X(_236_)
  );
  sky130_fd_sc_hd__a21o_1 _399_ (
    .A1(_279_),
    .A2(_264_),
    .B1(_282_),
    .X(_217_)
  );
  sky130_fd_sc_hd__and2_0 _400_ (
    .A(_279_),
    .B(_278_),
    .X(_215_)
  );
  sky130_fd_sc_hd__a21o_1 _401_ (
    .A1(_280_),
    .A2(_266_),
    .B1(_281_),
    .X(_218_)
  );
  sky130_fd_sc_hd__mux4_2 _402_ (
    .A0(_251_),
    .A1(_252_),
    .A2(_253_),
    .A3(_254_),
    .S0(_240_),
    .S1(_241_),
    .X(_271_)
  );
  sky130_fd_sc_hd__nor2_1 _403_ (
    .A(_242_),
    .B(_271_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__mux4_2 _404_ (
    .A0(_255_),
    .A1(_256_),
    .A2(_257_),
    .A3(_258_),
    .S0(_240_),
    .S1(_241_),
    .X(_273_)
  );
  sky130_fd_sc_hd__o21ai_0 _405_ (
    .A1(_260_),
    .A2(_273_),
    .B1(_280_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__o21ai_0 _406_ (
    .A1(_272_),
    .A2(_274_),
    .B1(_270_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nor2_1 _407_ (
    .A(_263_),
    .B(_266_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nand2_1 _408_ (
    .A(_219_),
    .B(_215_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__mux2_1 _409_ (
    .A0(_243_),
    .A1(_251_),
    .S(_275_),
    .X(_228_)
  );
  sky130_fd_sc_hd__mux2_1 _410_ (
    .A0(_244_),
    .A1(_252_),
    .S(_275_),
    .X(_229_)
  );
  sky130_fd_sc_hd__mux2_1 _411_ (
    .A0(_245_),
    .A1(_253_),
    .S(_275_),
    .X(_230_)
  );
  sky130_fd_sc_hd__mux2_1 _412_ (
    .A0(_246_),
    .A1(_254_),
    .S(_275_),
    .X(_231_)
  );
  sky130_fd_sc_hd__mux2_1 _413_ (
    .A0(_247_),
    .A1(_255_),
    .S(_275_),
    .X(_232_)
  );
  sky130_fd_sc_hd__mux2_1 _414_ (
    .A0(_248_),
    .A1(_256_),
    .S(_275_),
    .X(_233_)
  );
  sky130_fd_sc_hd__mux2_1 _415_ (
    .A0(_249_),
    .A1(_257_),
    .S(_275_),
    .X(_234_)
  );
  sky130_fd_sc_hd__mux2_1 _416_ (
    .A0(_250_),
    .A1(_258_),
    .S(_275_),
    .X(_235_)
  );
  sky130_fd_sc_hd__clkinv_1 _417_ (
    .A(_277_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__clkinv_1 _418_ (
    .A(_277_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__clkinv_1 _419_ (
    .A(_277_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__clkinv_1 _420_ (
    .A(_277_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__clkinv_1 _421_ (
    .A(_277_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__clkinv_1 _422_ (
    .A(_277_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__clkinv_1 _423_ (
    .A(_277_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__clkinv_1 _424_ (
    .A(_277_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__dfstp_2 _425_ (
    .CLK(\tx_inst.clk ),
    .D(_192_),
    .Q(\tx_inst.state [0]),
    .SET_B(_283_)
  );
  sky130_fd_sc_hd__dfrtp_1 _426_ (
    .CLK(\tx_inst.clk ),
    .D(_193_),
    .Q(\tx_inst.state [1]),
    .RESET_B(_284_)
  );
  sky130_fd_sc_hd__dfrtp_1 _427_ (
    .CLK(\tx_inst.clk ),
    .D(_190_),
    .Q(\tx_inst.state [2]),
    .RESET_B(_285_)
  );
  sky130_fd_sc_hd__dfrtp_1 _428_ (
    .CLK(\tx_inst.clk ),
    .D(_191_),
    .Q(\tx_inst.state [3]),
    .RESET_B(_286_)
  );
  sky130_fd_sc_hd__dfxtp_1 _429_ (
    .CLK(\tx_inst.clk ),
    .D(_292_),
    .Q(\tx_inst.data_reg [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _430_ (
    .CLK(\tx_inst.clk ),
    .D(_293_),
    .Q(\tx_inst.data_reg [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _431_ (
    .CLK(\tx_inst.clk ),
    .D(_294_),
    .Q(\tx_inst.data_reg [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _432_ (
    .CLK(\tx_inst.clk ),
    .D(_295_),
    .Q(\tx_inst.data_reg [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _433_ (
    .CLK(\tx_inst.clk ),
    .D(_296_),
    .Q(\tx_inst.data_reg [4])
  );
  sky130_fd_sc_hd__dfxtp_1 _434_ (
    .CLK(\tx_inst.clk ),
    .D(_297_),
    .Q(\tx_inst.data_reg [5])
  );
  sky130_fd_sc_hd__dfxtp_1 _435_ (
    .CLK(\tx_inst.clk ),
    .D(_298_),
    .Q(\tx_inst.data_reg [6])
  );
  sky130_fd_sc_hd__dfxtp_1 _436_ (
    .CLK(\tx_inst.clk ),
    .D(_299_),
    .Q(\tx_inst.data_reg [7])
  );
  sky130_fd_sc_hd__dfstp_2 _437_ (
    .CLK(\tx_inst.clk ),
    .D(_305_),
    .Q(\tx_inst.tx ),
    .SET_B(_287_)
  );
  sky130_fd_sc_hd__dfrtp_1 _438_ (
    .CLK(\tx_inst.clk ),
    .D(_300_),
    .Q(\tx_inst.done ),
    .RESET_B(_288_)
  );
  sky130_fd_sc_hd__dfrtp_1 _439_ (
    .CLK(\tx_inst.clk ),
    .D(_301_),
    .Q(\tx_inst.bit_count [0]),
    .RESET_B(_289_)
  );
  sky130_fd_sc_hd__dfrtp_1 _440_ (
    .CLK(\tx_inst.clk ),
    .D(_302_),
    .Q(\tx_inst.bit_count [1]),
    .RESET_B(_290_)
  );
  sky130_fd_sc_hd__dfrtp_1 _441_ (
    .CLK(\tx_inst.clk ),
    .D(_303_),
    .Q(\tx_inst.bit_count [2]),
    .RESET_B(_291_)
  );
  assign _242_ = \tx_inst.bit_count [2];
  assign _303_ = _239_;
  assign _241_ = \tx_inst.bit_count [1];
  assign _302_ = _238_;
  assign _240_ = \tx_inst.bit_count [0];
  assign _301_ = _237_;
  assign _259_ = \tx_inst.done ;
  assign _282_ = \tx_inst.state [3];
  assign _300_ = _236_;
  assign _279_ = \tx_inst.state [0];
  assign _280_ = \tx_inst.state [1];
  assign _281_ = \tx_inst.state [2];
  assign _278_ = \tx_inst.start ;
  assign _192_ = _217_;
  assign _190_ = _215_;
  assign _277_ = \tx_inst.reset ;
  assign _193_ = _218_;
  assign _251_ = \tx_inst.data_reg [0];
  assign _252_ = \tx_inst.data_reg [1];
  assign _253_ = \tx_inst.data_reg [2];
  assign _254_ = \tx_inst.data_reg [3];
  assign _255_ = \tx_inst.data_reg [4];
  assign _256_ = \tx_inst.data_reg [5];
  assign _257_ = \tx_inst.data_reg [6];
  assign _258_ = \tx_inst.data_reg [7];
  assign _305_ = _276_;
  assign _191_ = _216_;
  assign _283_ = _219_;
  assign _284_ = _220_;
  assign _285_ = _221_;
  assign _286_ = _222_;
  assign _243_ = \tx_inst.data [0];
  assign _292_ = _228_;
  assign _244_ = \tx_inst.data [1];
  assign _293_ = _229_;
  assign _245_ = \tx_inst.data [2];
  assign _294_ = _230_;
  assign _246_ = \tx_inst.data [3];
  assign _295_ = _231_;
  assign _247_ = \tx_inst.data [4];
  assign _296_ = _232_;
  assign _248_ = \tx_inst.data [5];
  assign _297_ = _233_;
  assign _249_ = \tx_inst.data [6];
  assign _298_ = _234_;
  assign _250_ = \tx_inst.data [7];
  assign _299_ = _235_;
  assign _287_ = _223_;
  assign _288_ = _224_;
  assign _289_ = _225_;
  assign _290_ = _226_;
  assign _291_ = _227_;
  assign \tx_inst.clk  = clk;
  assign \tx_inst.data  = tx_data;
  assign tx_done = \tx_inst.done ;
  assign \tx_inst.reset  = reset;
  assign \tx_inst.start  = start;
  assign tx_line = \tx_inst.tx ;
  assign _125_ = \rx_inst.done ;
  assign _160_ = \rx_inst.state [3];
  assign _188_ = _113_;
  assign _124_ = \rx_inst.data [7];
  assign _187_ = _112_;
  assign _123_ = \rx_inst.data [6];
  assign _186_ = _111_;
  assign _122_ = \rx_inst.data [5];
  assign _185_ = _110_;
  assign _121_ = \rx_inst.data [4];
  assign _184_ = _109_;
  assign _120_ = \rx_inst.data [3];
  assign _183_ = _108_;
  assign _119_ = \rx_inst.data [2];
  assign _182_ = _107_;
  assign _118_ = \rx_inst.data [1];
  assign _181_ = _106_;
  assign _117_ = \rx_inst.data [0];
  assign _180_ = _105_;
  assign _116_ = \rx_inst.bit_count [2];
  assign _179_ = _104_;
  assign _115_ = \rx_inst.bit_count [1];
  assign _178_ = _103_;
  assign _114_ = \rx_inst.bit_count [0];
  assign _177_ = _102_;
  assign _159_ = \rx_inst.state [2];
  assign _158_ = \rx_inst.state [1];
  assign _156_ = \rx_inst.rx ;
  assign _005_ = _085_;
  assign _157_ = \rx_inst.state [0];
  assign _004_ = _084_;
  assign _003_ = _083_;
  assign _002_ = _082_;
  assign _155_ = \rx_inst.reset ;
  assign _161_ = _086_;
  assign _162_ = _087_;
  assign _163_ = _088_;
  assign _164_ = _089_;
  assign _165_ = _090_;
  assign _166_ = _091_;
  assign _167_ = _092_;
  assign _168_ = _093_;
  assign _169_ = _094_;
  assign _170_ = _095_;
  assign _171_ = _096_;
  assign _172_ = _097_;
  assign _173_ = _098_;
  assign _174_ = _099_;
  assign _175_ = _100_;
  assign _176_ = _101_;
  assign \rx_inst.clk  = clk;
  assign rx_data = \rx_inst.data ;
  assign rx_done = \rx_inst.done ;
  assign \rx_inst.reset  = reset;
  assign \rx_inst.rx  = tx_line;
endmodule
