/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module full_adder(a, b, cin, sum, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output sum;
  wire sum;
  sky130_fd_sc_hd__xor3_1 _10_ (
    .A(_01_),
    .B(_00_),
    .C(_02_),
    .X(_04_)
  );
  sky130_fd_sc_hd__maj3_1 _11_ (
    .A(_01_),
    .B(_00_),
    .C(_02_),
    .X(_03_)
  );
  assign _01_ = b;
  assign _00_ = a;
  assign _02_ = cin;
  assign sum = _04_;
  assign cout = _03_;
endmodule
